// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table prescriptions_raw (data:dynamic) 
.create-or-alter table prescriptions_raw ingestion json mapping 'prescriptions_raw_mapping'
```
[{"Properties":{"Path":"$"},"column":"data","datatype":""}]
```
.create-merge table prescriptions_exploded (prescription_id:string, issue_date:datetime, patient_name:string, patient_id:int, medication_name:string, medication_dosage:string, medication_frequency:string) 
.alter table prescriptions_exploded policy update "[{\"IsEnabled\":true,\"Source\":\"prescriptions_raw\",\"Query\":\"prescriptions_raw | mv-expand med = data.medications | project prescription_id = tostring(data.prescription_id), issue_date = todatetime(data.issue_date), patient_name = tostring(data.patient.name), patient_id = toint(data.patient.id), medication_name = tostring(med.name), medication_dosage = tostring(med.dosage), medication_frequency = tostring(med.frequency)\",\"IsTransactional\":false,\"PropagateIngestionProperties\":false,\"ManagedIdentity\":null}]"
